/** Mission Planner HUD property catalog with display labels from MP CurrentState DisplayText attributes. */
export interface MissionPlannerProperty {
  key: string;
  label?: string;
  /** Selection order among chosen properties (0-based). */
  order?: number;
  /**
   * Flight messages lookup key: `{messageId}_{propertyName}` from MessageProcessingFactory /
   * MavMessageMapper DTOs. Unknown fields use `999_{key}`.
   */
  propertyValue: string;
}

/** Format: Full Text Name (short name), or short name only when label is unknown. */
export const MISSION_PLANNER_PROPERTIES: readonly MissionPlannerProperty[] = [
  { key: 'accelsq', label: "Accel Strength", propertyValue: '999_accelsq' },
  { key: 'accelsq2', label: "Accel2 Strength", propertyValue: '999_accelsq2' },
  { key: 'accelsq3', label: "Accel3 Strength", propertyValue: '999_accelsq3' },
  { key: 'ahrs2_alt', propertyValue: '999_ahrs2_alt' },
  { key: 'ahrs2_lat', propertyValue: '999_ahrs2_lat' },
  { key: 'ahrs2_lng', propertyValue: '999_ahrs2_lng' },
  { key: 'ahrs2_pitch', propertyValue: '999_ahrs2_pitch' },
  { key: 'ahrs2_roll', propertyValue: '999_ahrs2_roll' },
  { key: 'ahrs2_yaw', propertyValue: '999_ahrs2_yaw' },
  { key: 'airspeed', label: "AirSpeed (speed)", propertyValue: '74_airspeedMS' },
  { key: 'airspeed1_temp', label: "Airspeed1 Temperature", propertyValue: '999_airspeed1_temp' },
  { key: 'airspeed2_temp', label: "Airspeed2 Temperature", propertyValue: '999_airspeed2_temp' },
  { key: 'alt', label: "Altitude (alt)", propertyValue: '33_relativeAltitudeM' },
  { key: 'alt_error', label: "Altitude Error (dist)", propertyValue: '62_altErrorM' },
  { key: 'altasl', label: "Altitude (alt)", propertyValue: '33_aslAltitudeM' },
  { key: 'altasl2', label: "Altitude2 (dist)", propertyValue: '999_altasl2' },
  { key: 'altd100', propertyValue: '999_altd100' },
  { key: 'altd1000', propertyValue: '999_altd1000' },
  { key: 'altoffsethome', label: "Alt Home Offset (dist)", propertyValue: '999_altoffsethome' },
  { key: 'AOA', label: "AOA (deg)", propertyValue: '999_AOA' },
  { key: 'armed', propertyValue: '0_armed' },
  { key: 'aspd_error', label: "Airspeed Error (speed)", propertyValue: '62_aspdErrorMS' },
  { key: 'asratio', label: "Airspeed Ratio", propertyValue: '999_asratio' },
  { key: 'ax', label: "Accel X", propertyValue: '999_ax' },
  { key: 'ax2', label: "Accel2 X", propertyValue: '999_ax2' },
  { key: 'ax3', label: "Accel3 X", propertyValue: '999_ax3' },
  { key: 'ay', label: "Accel Y", propertyValue: '999_ay' },
  { key: 'ay2', label: "Accel2 Y", propertyValue: '999_ay2' },
  { key: 'ay3', label: "Accel3 Y", propertyValue: '999_ay3' },
  { key: 'az', label: "Accel Z", propertyValue: '999_az' },
  { key: 'az2', label: "Accel2 Z", propertyValue: '999_az2' },
  { key: 'az3', label: "Accel3 Z", propertyValue: '999_az3' },
  { key: 'AZToMAV', label: "Bearing to Mav (deg)", propertyValue: '999_AZToMAV' },
  { key: 'battery_cell1', propertyValue: '999_battery_cell1' },
  { key: 'battery_cell2', propertyValue: '999_battery_cell2' },
  { key: 'battery_cell3', propertyValue: '999_battery_cell3' },
  { key: 'battery_cell4', propertyValue: '999_battery_cell4' },
  { key: 'battery_cell5', propertyValue: '999_battery_cell5' },
  { key: 'battery_cell6', propertyValue: '999_battery_cell6' },
  { key: 'battery_cell7', propertyValue: '999_battery_cell7' },
  { key: 'battery_cell8', propertyValue: '999_battery_cell8' },
  { key: 'battery_cell9', propertyValue: '999_battery_cell9' },
  { key: 'battery_cell10', propertyValue: '999_battery_cell10' },
  { key: 'battery_cell11', propertyValue: '999_battery_cell11' },
  { key: 'battery_cell12', propertyValue: '999_battery_cell12' },
  { key: 'battery_cell13', propertyValue: '999_battery_cell13' },
  { key: 'battery_cell14', propertyValue: '999_battery_cell14' },
  { key: 'battery_kmleft', label: "Bat km left EST (km)", propertyValue: '999_battery_kmleft' },
  { key: 'battery_mahperkm', label: "Bat efficiency (mah/km)", propertyValue: '999_battery_mahperkm' },
  { key: 'battery_remaining', label: "Bat Remaining (%)", propertyValue: '1_batteryRemainingPct' },
  { key: 'battery_remaining2', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining2' },
  { key: 'battery_remaining3', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining3' },
  { key: 'battery_remaining4', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining4' },
  { key: 'battery_remaining5', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining5' },
  { key: 'battery_remaining6', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining6' },
  { key: 'battery_remaining7', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining7' },
  { key: 'battery_remaining8', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining8' },
  { key: 'battery_remaining9', label: "Bat Remaining (%)", propertyValue: '999_battery_remaining9' },
  { key: 'battery_remainmin', propertyValue: '999_battery_remainmin' },
  { key: 'battery_remainmin2', propertyValue: '999_battery_remainmin2' },
  { key: 'battery_remainmin3', propertyValue: '999_battery_remainmin3' },
  { key: 'battery_remainmin4', propertyValue: '999_battery_remainmin4' },
  { key: 'battery_remainmin5', propertyValue: '999_battery_remainmin5' },
  { key: 'battery_remainmin6', propertyValue: '999_battery_remainmin6' },
  { key: 'battery_remainmin7', propertyValue: '999_battery_remainmin7' },
  { key: 'battery_remainmin8', propertyValue: '999_battery_remainmin8' },
  { key: 'battery_remainmin9', propertyValue: '999_battery_remainmin9' },
  { key: 'battery_temp', propertyValue: '999_battery_temp' },
  { key: 'battery_temp2', propertyValue: '999_battery_temp2' },
  { key: 'battery_temp3', propertyValue: '999_battery_temp3' },
  { key: 'battery_temp4', propertyValue: '999_battery_temp4' },
  { key: 'battery_temp5', propertyValue: '999_battery_temp5' },
  { key: 'battery_temp6', propertyValue: '999_battery_temp6' },
  { key: 'battery_temp7', propertyValue: '999_battery_temp7' },
  { key: 'battery_temp8', propertyValue: '999_battery_temp8' },
  { key: 'battery_temp9', propertyValue: '999_battery_temp9' },
  { key: 'battery_usedmah', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah' },
  { key: 'battery_usedmah2', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah2' },
  { key: 'battery_usedmah3', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah3' },
  { key: 'battery_usedmah4', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah4' },
  { key: 'battery_usedmah5', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah5' },
  { key: 'battery_usedmah6', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah6' },
  { key: 'battery_usedmah7', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah7' },
  { key: 'battery_usedmah8', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah8' },
  { key: 'battery_usedmah9', label: "Bat used EST (mah)", propertyValue: '999_battery_usedmah9' },
  { key: 'battery_voltage', label: "Bat Voltage (V)", propertyValue: '1_batteryVoltageV' },
  { key: 'battery_voltage2', label: "Bat2 Voltage (V)", propertyValue: '999_battery_voltage2' },
  { key: 'battery_voltage3', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage3' },
  { key: 'battery_voltage4', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage4' },
  { key: 'battery_voltage5', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage5' },
  { key: 'battery_voltage6', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage6' },
  { key: 'battery_voltage7', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage7' },
  { key: 'battery_voltage8', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage8' },
  { key: 'battery_voltage9', label: "Bat Voltage (V)", propertyValue: '999_battery_voltage9' },
  { key: 'ber_error', label: "Bearing Error (deg)", propertyValue: '999_ber_error' },
  { key: 'boardvoltage', label: "Board Voltage", propertyValue: '999_boardvoltage' },
  { key: 'brklevel', propertyValue: '999_brklevel' },
  { key: 'campointa', propertyValue: '999_campointa' },
  { key: 'campointb', propertyValue: '999_campointb' },
  { key: 'campointc', propertyValue: '999_campointc' },
  { key: 'capabilities', propertyValue: '999_capabilities' },
  { key: 'ch1in', propertyValue: '999_ch1in' },
  { key: 'ch1out', propertyValue: '999_ch1out' },
  { key: 'ch1percent', propertyValue: '999_ch1percent' },
  { key: 'ch2in', propertyValue: '999_ch2in' },
  { key: 'ch2out', propertyValue: '999_ch2out' },
  { key: 'ch3in', propertyValue: '999_ch3in' },
  { key: 'ch3out', propertyValue: '999_ch3out' },
  { key: 'ch3percent', propertyValue: '74_throttlePct' },
  { key: 'ch4in', propertyValue: '999_ch4in' },
  { key: 'ch4out', propertyValue: '999_ch4out' },
  { key: 'ch5in', propertyValue: '999_ch5in' },
  { key: 'ch5out', propertyValue: '999_ch5out' },
  { key: 'ch6in', propertyValue: '999_ch6in' },
  { key: 'ch6out', propertyValue: '999_ch6out' },
  { key: 'ch7in', propertyValue: '999_ch7in' },
  { key: 'ch7out', propertyValue: '999_ch7out' },
  { key: 'ch8in', propertyValue: '999_ch8in' },
  { key: 'ch8out', propertyValue: '999_ch8out' },
  { key: 'ch9in', propertyValue: '999_ch9in' },
  { key: 'ch9out', propertyValue: '999_ch9out' },
  { key: 'ch10in', propertyValue: '999_ch10in' },
  { key: 'ch10out', propertyValue: '999_ch10out' },
  { key: 'ch11in', propertyValue: '999_ch11in' },
  { key: 'ch11out', propertyValue: '999_ch11out' },
  { key: 'ch12in', propertyValue: '999_ch12in' },
  { key: 'ch12out', propertyValue: '999_ch12out' },
  { key: 'ch13in', propertyValue: '999_ch13in' },
  { key: 'ch13out', propertyValue: '999_ch13out' },
  { key: 'ch14in', propertyValue: '999_ch14in' },
  { key: 'ch14out', propertyValue: '999_ch14out' },
  { key: 'ch15in', propertyValue: '999_ch15in' },
  { key: 'ch15out', propertyValue: '999_ch15out' },
  { key: 'ch16in', propertyValue: '999_ch16in' },
  { key: 'ch16out', propertyValue: '999_ch16out' },
  { key: 'ch17in', propertyValue: '999_ch17in' },
  { key: 'ch17out', propertyValue: '999_ch17out' },
  { key: 'ch18in', propertyValue: '999_ch18in' },
  { key: 'ch18out', propertyValue: '999_ch18out' },
  { key: 'ch19in', propertyValue: '999_ch19in' },
  { key: 'ch20out', propertyValue: '999_ch20out' },
  { key: 'ch21out', propertyValue: '999_ch21out' },
  { key: 'ch22out', propertyValue: '999_ch22out' },
  { key: 'ch23out', propertyValue: '999_ch23out' },
  { key: 'ch24out', propertyValue: '999_ch24out' },
  { key: 'ch25out', propertyValue: '999_ch25out' },
  { key: 'ch26out', propertyValue: '999_ch26out' },
  { key: 'ch27out', propertyValue: '999_ch27out' },
  { key: 'ch28out', propertyValue: '999_ch28out' },
  { key: 'ch29out', propertyValue: '999_ch29out' },
  { key: 'ch30out', propertyValue: '999_ch30out' },
  { key: 'ch31out', propertyValue: '999_ch31out' },
  { key: 'ch32out', propertyValue: '999_ch32out' },
  { key: 'climbrate', label: "ClimbRate (speed)", propertyValue: '74_climbMS' },
  { key: 'connected', propertyValue: '999_connected' },
  { key: 'crit_AOA', label: "Crit AOA (deg)", propertyValue: '999_crit_AOA' },
  { key: 'current', label: "Bat Current (Amps)", propertyValue: '1_batteryCurrentA' },
  { key: 'current2', label: "Bat2 Current (Amps)", propertyValue: '999_current2' },
  { key: 'current3', label: "Bat3 Current (Amps)", propertyValue: '999_current3' },
  { key: 'current4', label: "Bat4 Current (Amps)", propertyValue: '999_current4' },
  { key: 'current5', label: "Bat5 Current (Amps)", propertyValue: '999_current5' },
  { key: 'current6', label: "Bat6 Current (Amps)", propertyValue: '999_current6' },
  { key: 'current7', label: "Bat7 Current (Amps)", propertyValue: '999_current7' },
  { key: 'current8', label: "Bat8 Current (Amps)", propertyValue: '999_current8' },
  { key: 'current9', label: "Bat9 Current (Amps)", propertyValue: '999_current9' },
  { key: 'DistFromMovingBase', label: "Dist to Moving Base (dist)", propertyValue: '999_DistFromMovingBase' },
  { key: 'DistRSSIRemain', label: "Sik Radio est dist (m)", propertyValue: '999_DistRSSIRemain' },
  { key: 'DistToHome', label: "Dist to Home (dist)", propertyValue: '999_DistToHome' },
  { key: 'distTraveled', label: "Dist Traveled (dist)", propertyValue: '999_distTraveled' },
  { key: 'efi_baro', label: "EFI Baro Pressure (kPa)", propertyValue: '999_efi_baro' },
  { key: 'efi_exhausttemp', propertyValue: '999_efi_exhausttemp' },
  { key: 'efi_fuelconsumed', label: "EFI Fuel Consumed (cm3)", propertyValue: '999_efi_fuelconsumed' },
  { key: 'efi_fuelflow', label: "EFI Fuel Flow (cm3/min)", propertyValue: '999_efi_fuelflow' },
  { key: 'efi_fuelpressure', label: "EFI Fuel Pressure (kPa)", propertyValue: '999_efi_fuelpressure' },
  { key: 'efi_headtemp', label: "EFI Head Temp (C)", propertyValue: '999_efi_headtemp' },
  { key: 'efi_health', label: "EFI Health", propertyValue: '999_efi_health' },
  { key: 'efi_intaketemp', label: "EFI Intake Temp (C)", propertyValue: '999_efi_intaketemp' },
  { key: 'efi_load', label: "EFI Load (%)", propertyValue: '999_efi_load' },
  { key: 'efi_rpm', label: "EFI rpm", propertyValue: '999_efi_rpm' },
  { key: 'ekfcompv', propertyValue: '999_ekfcompv' },
  { key: 'ekfflags', propertyValue: '999_ekfflags' },
  { key: 'ekfposhor', propertyValue: '999_ekfposhor' },
  { key: 'ekfposvert', propertyValue: '999_ekfposvert' },
  { key: 'ekfstatus', propertyValue: '999_ekfstatus' },
  { key: 'ekfteralt', propertyValue: '999_ekfteralt' },
  { key: 'ekfvelv', propertyValue: '999_ekfvelv' },
  { key: 'ELToMAV', label: "Elevation to Mav (deg)", propertyValue: '999_ELToMAV' },
  { key: 'errors_count1', label: "Error Type", propertyValue: '999_errors_count1' },
  { key: 'errors_count2', label: "Error Type", propertyValue: '999_errors_count2' },
  { key: 'errors_count3', label: "Error Type", propertyValue: '999_errors_count3' },
  { key: 'errors_count4', label: "Error Count", propertyValue: '999_errors_count4' },
  { key: 'esc1_curr', propertyValue: '999_esc1_curr' },
  { key: 'esc1_rpm', propertyValue: '999_esc1_rpm' },
  { key: 'esc1_temp', propertyValue: '999_esc1_temp' },
  { key: 'esc1_volt', propertyValue: '999_esc1_volt' },
  { key: 'esc2_curr', propertyValue: '999_esc2_curr' },
  { key: 'esc2_rpm', propertyValue: '999_esc2_rpm' },
  { key: 'esc2_temp', propertyValue: '999_esc2_temp' },
  { key: 'esc2_volt', propertyValue: '999_esc2_volt' },
  { key: 'esc3_curr', propertyValue: '999_esc3_curr' },
  { key: 'esc3_rpm', propertyValue: '999_esc3_rpm' },
  { key: 'esc3_temp', propertyValue: '999_esc3_temp' },
  { key: 'esc3_volt', propertyValue: '999_esc3_volt' },
  { key: 'esc4_curr', propertyValue: '999_esc4_curr' },
  { key: 'esc4_rpm', propertyValue: '999_esc4_rpm' },
  { key: 'esc4_temp', propertyValue: '999_esc4_temp' },
  { key: 'esc4_volt', propertyValue: '999_esc4_volt' },
  { key: 'esc5_curr', propertyValue: '999_esc5_curr' },
  { key: 'esc5_rpm', propertyValue: '999_esc5_rpm' },
  { key: 'esc5_temp', propertyValue: '999_esc5_temp' },
  { key: 'esc5_volt', propertyValue: '999_esc5_volt' },
  { key: 'esc6_curr', propertyValue: '999_esc6_curr' },
  { key: 'esc6_rpm', propertyValue: '999_esc6_rpm' },
  { key: 'esc6_temp', propertyValue: '999_esc6_temp' },
  { key: 'esc6_volt', propertyValue: '999_esc6_volt' },
  { key: 'esc7_curr', propertyValue: '999_esc7_curr' },
  { key: 'esc7_rpm', propertyValue: '999_esc7_rpm' },
  { key: 'esc7_temp', propertyValue: '999_esc7_temp' },
  { key: 'esc7_volt', propertyValue: '999_esc7_volt' },
  { key: 'esc8_curr', propertyValue: '999_esc8_curr' },
  { key: 'esc8_rpm', propertyValue: '999_esc8_rpm' },
  { key: 'esc8_temp', propertyValue: '999_esc8_temp' },
  { key: 'esc8_volt', propertyValue: '999_esc8_volt' },
  { key: 'esc9_curr', propertyValue: '999_esc9_curr' },
  { key: 'esc9_rpm', propertyValue: '999_esc9_rpm' },
  { key: 'esc9_temp', propertyValue: '999_esc9_temp' },
  { key: 'esc9_volt', propertyValue: '999_esc9_volt' },
  { key: 'esc10_curr', propertyValue: '999_esc10_curr' },
  { key: 'esc10_rpm', propertyValue: '999_esc10_rpm' },
  { key: 'esc10_temp', propertyValue: '999_esc10_temp' },
  { key: 'esc10_volt', propertyValue: '999_esc10_volt' },
  { key: 'esc11_curr', propertyValue: '999_esc11_curr' },
  { key: 'esc11_rpm', propertyValue: '999_esc11_rpm' },
  { key: 'esc11_temp', propertyValue: '999_esc11_temp' },
  { key: 'esc11_volt', propertyValue: '999_esc11_volt' },
  { key: 'esc12_curr', propertyValue: '999_esc12_curr' },
  { key: 'esc12_rpm', propertyValue: '999_esc12_rpm' },
  { key: 'esc12_temp', propertyValue: '999_esc12_temp' },
  { key: 'esc12_volt', propertyValue: '999_esc12_volt' },
  { key: 'esc13_curr', propertyValue: '999_esc13_curr' },
  { key: 'esc13_rpm', propertyValue: '999_esc13_rpm' },
  { key: 'esc13_temp', propertyValue: '999_esc13_temp' },
  { key: 'esc13_volt', propertyValue: '999_esc13_volt' },
  { key: 'esc14_curr', propertyValue: '999_esc14_curr' },
  { key: 'esc14_rpm', propertyValue: '999_esc14_rpm' },
  { key: 'esc14_temp', propertyValue: '999_esc14_temp' },
  { key: 'esc14_volt', propertyValue: '999_esc14_volt' },
  { key: 'esc15_curr', propertyValue: '999_esc15_curr' },
  { key: 'esc15_rpm', propertyValue: '999_esc15_rpm' },
  { key: 'esc15_temp', propertyValue: '999_esc15_temp' },
  { key: 'esc15_volt', propertyValue: '999_esc15_volt' },
  { key: 'esc16_curr', propertyValue: '999_esc16_curr' },
  { key: 'esc16_rpm', propertyValue: '999_esc16_rpm' },
  { key: 'esc16_temp', propertyValue: '999_esc16_temp' },
  { key: 'esc16_volt', propertyValue: '999_esc16_volt' },
  { key: 'failsafe', label: "Failsafe", propertyValue: '999_failsafe' },
  { key: 'fenceb_count', label: "Breach count", propertyValue: '999_fenceb_count' },
  { key: 'fenceb_status', label: "Breach status", propertyValue: '999_fenceb_status' },
  { key: 'fenceb_type', label: "Breach type", propertyValue: '999_fenceb_type' },
  { key: 'fixedp', propertyValue: '999_fixedp' },
  { key: 'freemem', propertyValue: '999_freemem' },
  { key: 'gen_current', propertyValue: '999_gen_current' },
  { key: 'gen_maint_time', propertyValue: '999_gen_maint_time' },
  { key: 'gen_runtime', propertyValue: '999_gen_runtime' },
  { key: 'gen_speed', propertyValue: '999_gen_speed' },
  { key: 'gen_status', propertyValue: '999_gen_status' },
  { key: 'gen_voltage', propertyValue: '999_gen_voltage' },
  { key: 'GeoFenceDist', propertyValue: '999_GeoFenceDist' },
  { key: 'gimballat', propertyValue: '999_gimballat' },
  { key: 'gimballng', propertyValue: '999_gimballng' },
  { key: 'glide_ratio', label: "Glide Ratio", propertyValue: '999_glide_ratio' },
  { key: 'gpsh_acc', label: "H Acc (m)", propertyValue: '999_gpsh_acc' },
  { key: 'gpsh_acc2', label: "H Acc2 (m)", propertyValue: '999_gpsh_acc2' },
  { key: 'gpshdg_acc', label: "Heading Accuracy", propertyValue: '999_gpshdg_acc' },
  { key: 'gpshdg_acc2', label: "Heading Accuracy", propertyValue: '999_gpshdg_acc2' },
  { key: 'gpshdop', label: "Gps HDOP", propertyValue: '999_gpshdop' },
  { key: 'gpshdop2', label: "Gps HDOP2", propertyValue: '999_gpshdop2' },
  { key: 'gpsstatus', label: "Gps Status", propertyValue: '24_fixType' },
  { key: 'gpsstatus2', label: "Gps Status2", propertyValue: '999_gpsstatus2' },
  { key: 'gpsv_acc', label: "V Acc (m)", propertyValue: '999_gpsv_acc' },
  { key: 'gpsv_acc2', label: "V Acc2 (m)", propertyValue: '999_gpsv_acc2' },
  { key: 'gpsvel_acc', label: "Velocity Accuracy", propertyValue: '999_gpsvel_acc' },
  { key: 'gpsvel_acc2', label: "Velocity Accuracy", propertyValue: '999_gpsvel_acc2' },
  { key: 'gpsyaw', label: "GPS Yaw (deg)", propertyValue: '999_gpsyaw' },
  { key: 'gpsyaw2', label: "GPS Yaw (deg)", propertyValue: '999_gpsyaw2' },
  { key: 'groundcourse', label: "GroundCourse (deg)", propertyValue: '999_groundcourse' },
  { key: 'groundcourse2', label: "GroundCourse2 (deg)", propertyValue: '999_groundcourse2' },
  { key: 'groundspeed', label: "GroundSpeed (speed)", propertyValue: '74_groundSpeedMS' },
  { key: 'groundspeed2', propertyValue: '999_groundspeed2' },
  { key: 'gx', label: "Gyro X", propertyValue: '999_gx' },
  { key: 'gx2', label: "Gyro2 X", propertyValue: '999_gx2' },
  { key: 'gx3', label: "Gyro3 X", propertyValue: '999_gx3' },
  { key: 'gy', label: "Gyro Y", propertyValue: '999_gy' },
  { key: 'gy2', label: "Gyro2 Y", propertyValue: '999_gy2' },
  { key: 'gy3', label: "Gyro3 Y", propertyValue: '999_gy3' },
  { key: 'gyrosq', label: "Gyro Strength", propertyValue: '999_gyrosq' },
  { key: 'gyrosq2', label: "Gyro2 Strength", propertyValue: '999_gyrosq2' },
  { key: 'gyrosq3', label: "Gyro3 Strength", propertyValue: '999_gyrosq3' },
  { key: 'gz', label: "Gyro Z", propertyValue: '999_gz' },
  { key: 'gz2', label: "Gyro2 Z", propertyValue: '999_gz2' },
  { key: 'gz3', label: "Gyro3 Z", propertyValue: '999_gz3' },
  { key: 'HomeAlt', propertyValue: '242_altitudeM' },
  { key: 'horizondist', label: "Horizon Dist (dist)", propertyValue: '999_horizondist' },
  { key: 'hwvoltage', label: "HW Voltage", propertyValue: '999_hwvoltage' },
  { key: 'hygrohumi1', label: "hygrohumi1 (c%)", propertyValue: '999_hygrohumi1' },
  { key: 'hygrohumi2', label: "hygrohumi2 (c%)", propertyValue: '999_hygrohumi2' },
  { key: 'hygrotemp1', label: "hygrotemp1 (cdegC)", propertyValue: '999_hygrotemp1' },
  { key: 'hygrotemp2', label: "hygrotemp2 (cdegC)", propertyValue: '999_hygrotemp2' },
  { key: 'i2cerrors', propertyValue: '999_i2cerrors' },
  { key: 'imu1_temp', label: "IMU1 Temperature", propertyValue: '999_imu1_temp' },
  { key: 'imu2_temp', label: "IMU2 Temperature", propertyValue: '999_imu2_temp' },
  { key: 'imu3_temp', label: "IMU3 Temperature", propertyValue: '999_imu3_temp' },
  { key: 'kIndex', propertyValue: '999_kIndex' },
  { key: 'landed', propertyValue: '999_landed' },
  { key: 'landed_state', propertyValue: '999_landed_state' },
  { key: 'lat', label: "Latitude (dd)", propertyValue: '33_latitudeDeg' },
  { key: 'lat2', label: "Latitude2 (dd)", propertyValue: '999_lat2' },
  { key: 'linkqualitygcs', propertyValue: '998_linkQualityGcs' },
  { key: 'lng', label: "Longitude (dd)", propertyValue: '33_longitudeDeg' },
  { key: 'lng2', label: "Longitude2 (dd)", propertyValue: '999_lng2' },
  { key: 'load', propertyValue: '1_load' },
  { key: 'localsnrdb', label: "Sik Radio snr", propertyValue: '999_localsnrdb' },
  { key: 'lowairspeed', propertyValue: '999_lowairspeed' },
  { key: 'lowgroundspeed', propertyValue: '999_lowgroundspeed' },
  { key: 'magfield', label: "Mag Field", propertyValue: '999_magfield' },
  { key: 'magfield2', label: "Mag2 Field", propertyValue: '999_magfield2' },
  { key: 'magfield3', label: "Mag3 Field", propertyValue: '999_magfield3' },
  { key: 'mcumaxvolt', label: "mcu max voltage", propertyValue: '999_mcumaxvolt' },
  { key: 'mcuminvolt', label: "mcu min voltage", propertyValue: '999_mcuminvolt' },
  { key: 'mcutemp', label: "mcu temperature", propertyValue: '999_mcutemp' },
  { key: 'mcuvoltage', label: "mcu voltage", propertyValue: '999_mcuvoltage' },
  { key: 'messageHighSeverity', propertyValue: '999_messageHighSeverity' },
  { key: 'mx', label: "Mag X", propertyValue: '999_mx' },
  { key: 'mx2', label: "Mag2 X", propertyValue: '999_mx2' },
  { key: 'mx3', label: "Mag3 X", propertyValue: '999_mx3' },
  { key: 'my', label: "Mag Y", propertyValue: '999_my' },
  { key: 'my2', label: "Mag2 Y", propertyValue: '999_my2' },
  { key: 'my3', label: "Mag3 Y", propertyValue: '999_my3' },
  { key: 'mz', label: "Mag Z", propertyValue: '999_mz' },
  { key: 'mz2', label: "Mag2 Z", propertyValue: '999_mz2' },
  { key: 'mz3', label: "Mag3 Z", propertyValue: '999_mz3' },
  { key: 'nav_bearing', label: "Bearing Target (deg)", propertyValue: '62_navBearing' },
  { key: 'nav_pitch', label: "Pitch Target (deg)", propertyValue: '62_navPitch' },
  { key: 'nav_roll', label: "Roll Target (deg)", propertyValue: '62_navRoll' },
  { key: 'noise', label: "Sik Radio noise", propertyValue: '166_noise' },
  { key: 'opt_m_x', label: "flow_comp_m_x", propertyValue: '999_opt_m_x' },
  { key: 'opt_m_y', label: "flow_comp_m_y", propertyValue: '999_opt_m_y' },
  { key: 'opt_qua', label: "flow quality", propertyValue: '999_opt_qua' },
  { key: 'opt_x', label: "flow_x", propertyValue: '999_opt_x' },
  { key: 'opt_y', label: "flow_y", propertyValue: '999_opt_y' },
  { key: 'packetdropremote', propertyValue: '999_packetdropremote' },
  { key: 'pidachieved', propertyValue: '999_pidachieved' },
  { key: 'pidaxis', propertyValue: '999_pidaxis' },
  { key: 'pidD', propertyValue: '999_pidD' },
  { key: 'piddesired', propertyValue: '999_piddesired' },
  { key: 'pidff', propertyValue: '999_pidff' },
  { key: 'pidl', propertyValue: '999_pidl' },
  { key: 'pidP', propertyValue: '999_pidP' },
  { key: 'pidPDmod', propertyValue: '999_pidPDmod' },
  { key: 'pidSRate', propertyValue: '999_pidSRate' },
  { key: 'pidSRateAccZ', propertyValue: '999_pidSRateAccZ' },
  { key: 'pidSRateLanding', propertyValue: '999_pidSRateLanding' },
  { key: 'pidSRatePitch', propertyValue: '999_pidSRatePitch' },
  { key: 'pidSRateRoll', propertyValue: '999_pidSRateRoll' },
  { key: 'pidSRateSteer', propertyValue: '999_pidSRateSteer' },
  { key: 'pidSRateYaw', propertyValue: '999_pidSRateYaw' },
  { key: 'pitch', label: "Pitch (deg)", propertyValue: '30_pitchDeg' },
  { key: 'posd', label: "Down", propertyValue: '999_posd' },
  { key: 'pose', label: "East", propertyValue: '999_pose' },
  { key: 'posn', label: "North", propertyValue: '999_posn' },
  { key: 'prearmstatus', propertyValue: '999_prearmstatus' },
  { key: 'press_abs', propertyValue: '999_press_abs' },
  { key: 'press_abs2', propertyValue: '999_press_abs2' },
  { key: 'press_temp', propertyValue: '999_press_temp' },
  { key: 'press_temp2', propertyValue: '999_press_temp2' },
  { key: 'QNH', propertyValue: '999_QNH' },
  { key: 'radius', label: "Turn Radius (dist)", propertyValue: '999_radius' },
  { key: 'rangefinder1', label: "RangeFinder1 (cm)", propertyValue: '999_rangefinder1' },
  { key: 'rangefinder2', label: "RangeFinder2 (cm)", propertyValue: '999_rangefinder2' },
  { key: 'rangefinder3', label: "RangeFinder3 (cm)", propertyValue: '999_rangefinder3' },
  { key: 'rangefinder4', label: "RangeFinder4 (cm)", propertyValue: '999_rangefinder4' },
  { key: 'rangefinder5', label: "RangeFinder5 (cm)", propertyValue: '999_rangefinder5' },
  { key: 'rangefinder6', label: "RangeFinder6 (cm)", propertyValue: '999_rangefinder6' },
  { key: 'rangefinder7', label: "RangeFinder7 (cm)", propertyValue: '999_rangefinder7' },
  { key: 'rangefinder8', label: "RangeFinder8 (cm)", propertyValue: '999_rangefinder8' },
  { key: 'rangefinder9', label: "RangeFinder9 (cm)", propertyValue: '999_rangefinder9' },
  { key: 'rangefinder10', label: "RangeFinder10 (cm)", propertyValue: '999_rangefinder10' },
  { key: 'rateattitude', propertyValue: '999_rateattitude' },
  { key: 'rateposition', propertyValue: '999_rateposition' },
  { key: 'raterc', propertyValue: '999_raterc' },
  { key: 'ratesensors', propertyValue: '999_ratesensors' },
  { key: 'ratestatus', propertyValue: '999_ratestatus' },
  { key: 'remnoise', label: "Sik Radio remote noise", propertyValue: '166_remNoise' },
  { key: 'remotesnrdb', label: "Sik Radio remote snr", propertyValue: '999_remotesnrdb' },
  { key: 'remrssi', label: "Sik Radio remote rssi", propertyValue: '166_remRssi' },
  { key: 'roll', label: "Roll (deg)", propertyValue: '30_rollDeg' },
  { key: 'rpm1', propertyValue: '999_rpm1' },
  { key: 'rpm2', propertyValue: '999_rpm2' },
  { key: 'rssi', label: "Sik Radio rssi", propertyValue: '166_rssi' },
  { key: 'rxerrors', propertyValue: '166_rxErrors' },
  { key: 'rxrssi', label: "RX Rssi", propertyValue: '999_rxrssi' },
  { key: 'safetyactive', propertyValue: '999_safetyactive' },
  { key: 'satcount', label: "Sat Count", propertyValue: '24_satellitesVisible' },
  { key: 'satcount2', label: "Sat Count2", propertyValue: '999_satcount2' },
  { key: 'satcountB', label: "Sat Count Blend", propertyValue: '999_satcountB' },
  { key: 'servovoltage', label: "Servo Rail Voltage", propertyValue: '999_servovoltage' },
  { key: 'sonarrange', label: "Sonar Range (alt)", propertyValue: '999_sonarrange' },
  { key: 'sonarvoltage', label: "Sonar Voltage (Volt)", propertyValue: '999_sonarvoltage' },
  { key: 'speedup', propertyValue: '999_speedup' },
  { key: 'SSA', label: "SSA (deg)", propertyValue: '999_SSA' },
  { key: 'target_bearing', label: "Bearing Target (deg)", propertyValue: '62_targetBearing' },
  { key: 'targetairspeed', label: "Airspeed Target (speed)", propertyValue: '999_targetairspeed' },
  { key: 'targetalt', propertyValue: '999_targetalt' },
  { key: 'targetaltd100', propertyValue: '999_targetaltd100' },
  { key: 'ter_alt', label: "Terrain GL", propertyValue: '999_ter_alt' },
  { key: 'ter_curalt', label: "Terrain AGL", propertyValue: '999_ter_curalt' },
  { key: 'ter_load', propertyValue: '999_ter_load' },
  { key: 'ter_pend', propertyValue: '999_ter_pend' },
  { key: 'ter_space', propertyValue: '999_ter_space' },
  { key: 'terrainactive', propertyValue: '999_terrainactive' },
  { key: 'timeInAir', label: "Time in Air (sec)", propertyValue: '998_timeSinceArmSec' },
  { key: 'timeInAirMinSec', label: "Time in Air (min.sec)", propertyValue: '998_timeSinceArmSec' },
  { key: 'timeincelastshot', propertyValue: '999_timeincelastshot' },
  { key: 'toh', label: "Time over Home (sec)", propertyValue: '999_toh' },
  { key: 'tot', label: "Time over Target (sec)", propertyValue: '999_tot' },
  { key: 'turng', label: "Turn Gs (load)", propertyValue: '999_turng' },
  { key: 'turnrate', label: "Turn Rate (speed)", propertyValue: '999_turnrate' },
  { key: 'txbuffer', propertyValue: '166_txBufPct' },
  { key: 'uid', propertyValue: '999_uid' },
  { key: 'verticalspeed', label: "Vertical Speed (speed)", propertyValue: '999_verticalspeed' },
  { key: 'verticalspeed_fpm', label: "Vertical Speed (fpm)", propertyValue: '999_verticalspeed_fpm' },
  { key: 'vibeclip0', propertyValue: '999_vibeclip0' },
  { key: 'vibeclip1', propertyValue: '999_vibeclip1' },
  { key: 'vibeclip2', propertyValue: '999_vibeclip2' },
  { key: 'vibex', propertyValue: '999_vibex' },
  { key: 'vibey', propertyValue: '999_vibey' },
  { key: 'vibez', propertyValue: '999_vibez' },
  { key: 'vlen', propertyValue: '999_vlen' },
  { key: 'voltageflag', label: "Voltage Flags", propertyValue: '999_voltageflag' },
  { key: 'vtol_state', propertyValue: '999_vtol_state' },
  { key: 'vx', label: "Velocity X (ms)", propertyValue: '999_vx' },
  { key: 'vy', label: "Velocity Y (ms)", propertyValue: '999_vy' },
  { key: 'vz', label: "Velocity Z (ms)", propertyValue: '999_vz' },
  { key: 'watts', label: "Bat Watts", propertyValue: '999_watts' },
  { key: 'wind_dir', label: "Wind Direction (Deg)", propertyValue: '168_directionDeg' },
  { key: 'wind_vel', label: "Wind Velocity (speed)", propertyValue: '168_speedMS' },
  { key: 'wp_dist', label: "Dist to WP (dist)", propertyValue: '62_wpDistM' },
  { key: 'wpno', label: "WP No", propertyValue: '42_seq' },
  { key: 'xpdr_adsb_tx_sys_fail', label: "ADSB Tx System Failure", propertyValue: '999_xpdr_adsb_tx_sys_fail' },
  { key: 'xpdr_airborne_status', label: "Airborne", propertyValue: '999_xpdr_airborne_status' },
  { key: 'xpdr_board_temperature', label: "Board Temperature in C", propertyValue: '999_xpdr_board_temperature' },
  { key: 'xpdr_es1090_tx_enabled', label: "Transponder 1090ES Tx Enabled", propertyValue: '999_xpdr_es1090_tx_enabled' },
  { key: 'xpdr_gps_no_fix', label: "GPS No Fix", propertyValue: '999_xpdr_gps_no_fix' },
  { key: 'xpdr_gps_unavail', label: "GPS Unavailable", propertyValue: '999_xpdr_gps_unavail' },
  { key: 'xpdr_ident_active', label: "Ident Active", propertyValue: '999_xpdr_ident_active' },
  { key: 'xpdr_interrogated_since_last', label: "Interrogated since last", propertyValue: '999_xpdr_interrogated_since_last' },
  { key: 'xpdr_maint_req', label: "Maintainence Required", propertyValue: '999_xpdr_maint_req' },
  { key: 'xpdr_mode_A_enabled', label: "Transponder Mode A Reply Enabled", propertyValue: '999_xpdr_mode_A_enabled' },
  { key: 'xpdr_mode_A_squawk_code', label: "Transponder Mode A squawk code", propertyValue: '999_xpdr_mode_A_squawk_code' },
  { key: 'xpdr_mode_C_enabled', label: "Transponder Mode C Reply Enabled", propertyValue: '999_xpdr_mode_C_enabled' },
  { key: 'xpdr_mode_S_enabled', label: "Transponder Mode S Reply Enabled", propertyValue: '999_xpdr_mode_S_enabled' },
  { key: 'xpdr_nacp', label: "NACp", propertyValue: '999_xpdr_nacp' },
  { key: 'xpdr_nic', label: "NIC", propertyValue: '999_xpdr_nic' },
  { key: 'xpdr_status_pending', label: "Status Update Pending", propertyValue: '999_xpdr_status_pending' },
  { key: 'xpdr_status_unavail', label: "Ping200X No Status Message Recieved", propertyValue: '999_xpdr_status_unavail' },
  { key: 'xpdr_x_bit_status', label: "X-bit Status", propertyValue: '999_xpdr_x_bit_status' },
  { key: 'xtrack_error', label: "Xtrack Error (m)", propertyValue: '62_xtrackErrorM' },
  { key: 'yaw', label: "Yaw (deg)", propertyValue: '30_yawDeg' },
] as const;

export type MissionPlannerPropertyKey = (typeof MISSION_PLANNER_PROPERTIES)[number]['key'];
